/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.myemp.method;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class BasisVO extends SuperVO {
	private java.lang.String pk_method;
	private java.lang.String pk_basis;
	private nc.vo.pub.lang.UFBoolean selected;
	private java.lang.String allocdimen;
	private java.lang.String type;
	private java.lang.String pk_factor;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_METHOD = "pk_method";
	public static final String PK_BASIS = "pk_basis";
	public static final String SELECTED = "selected";
	public static final String ALLOCDIMEN = "allocdimen";
	public static final String TYPE = "type";
	public static final String PK_FACTOR = "pk_factor";
			
	/**
	 * 属性pk_method的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_method () {
		return pk_method;
	}   
	/**
	 * 属性pk_method的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newPk_method java.lang.String
	 */
	public void setPk_method (java.lang.String newPk_method ) {
	 	this.pk_method = newPk_method;
	} 	  
	/**
	 * 属性pk_basis的Getter方法.属性名：分摊依据主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_basis () {
		return pk_basis;
	}   
	/**
	 * 属性pk_basis的Setter方法.属性名：分摊依据主键
	 * 创建日期:
	 * @param newPk_basis java.lang.String
	 */
	public void setPk_basis (java.lang.String newPk_basis ) {
	 	this.pk_basis = newPk_basis;
	} 	  
	/**
	 * 属性selected的Getter方法.属性名：选择
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getSelected () {
		return selected;
	}   
	/**
	 * 属性selected的Setter方法.属性名：选择
	 * 创建日期:
	 * @param newSelected nc.vo.pub.lang.UFBoolean
	 */
	public void setSelected (nc.vo.pub.lang.UFBoolean newSelected ) {
	 	this.selected = newSelected;
	} 	  
	/**
	 * 属性allocdimen的Getter方法.属性名：分摊维度
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getAllocdimen () {
		return allocdimen;
	}   
	/**
	 * 属性allocdimen的Setter方法.属性名：分摊维度
	 * 创建日期:
	 * @param newAllocdimen java.lang.String
	 */
	public void setAllocdimen (java.lang.String newAllocdimen ) {
	 	this.allocdimen = newAllocdimen;
	} 	  
	/**
	 * 属性type的Getter方法.属性名：类型
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getType () {
		return type;
	}   
	/**
	 * 属性type的Setter方法.属性名：类型
	 * 创建日期:
	 * @param newType java.lang.String
	 */
	public void setType (java.lang.String newType ) {
	 	this.type = newType;
	} 	  
	/**
	 * 属性pk_factor的Getter方法.属性名：要素
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_factor () {
		return pk_factor;
	}   
	/**
	 * 属性pk_factor的Setter方法.属性名：要素
	 * 创建日期:
	 * @param newPk_factor java.lang.String
	 */
	public void setPk_factor (java.lang.String newPk_factor ) {
	 	this.pk_factor = newPk_factor;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "pk_method";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_basis";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "myemp_basis";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "myemp_basis";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public BasisVO() {
		super();	
	}    
} 


