/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.myemp.emp;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class EmpVO extends SuperVO {
	private java.lang.String emp_id;
	private java.lang.String name;
	private java.lang.String code;
	private java.lang.Integer age;
	private java.lang.String job;
	private nc.vo.pub.lang.UFDouble salary;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String EMP_ID = "emp_id";
	public static final String NAME = "name";
	public static final String CODE = "code";
	public static final String AGE = "age";
	public static final String JOB = "job";
	public static final String SALARY = "salary";
			
	/**
	 * 属性emp_id的Getter方法.属性名：员工ID
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getEmp_id () {
		return emp_id;
	}   
	/**
	 * 属性emp_id的Setter方法.属性名：员工ID
	 * 创建日期:
	 * @param newEmp_id java.lang.String
	 */
	public void setEmp_id (java.lang.String newEmp_id ) {
	 	this.emp_id = newEmp_id;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：员工姓名
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：员工姓名
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性code的Getter方法.属性名：员工编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.属性名：员工编码
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性age的Getter方法.属性名：员工年龄
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getAge () {
		return age;
	}   
	/**
	 * 属性age的Setter方法.属性名：员工年龄
	 * 创建日期:
	 * @param newAge java.lang.Integer
	 */
	public void setAge (java.lang.Integer newAge ) {
	 	this.age = newAge;
	} 	  
	/**
	 * 属性job的Getter方法.属性名：员工工作
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getJob () {
		return job;
	}   
	/**
	 * 属性job的Setter方法.属性名：员工工作
	 * 创建日期:
	 * @param newJob java.lang.String
	 */
	public void setJob (java.lang.String newJob ) {
	 	this.job = newJob;
	} 	  
	/**
	 * 属性salary的Getter方法.属性名：员工薪水
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getSalary () {
		return salary;
	}   
	/**
	 * 属性salary的Setter方法.属性名：员工薪水
	 * 创建日期:
	 * @param newSalary nc.vo.pub.lang.UFDouble
	 */
	public void setSalary (nc.vo.pub.lang.UFDouble newSalary ) {
	 	this.salary = newSalary;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "emp_id";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "myemp";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "myemp";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public EmpVO() {
		super();	
	}    
} 


