/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.myemp.mng;
	
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class Emp extends SuperVO {
	private java.lang.String d_id;
	private java.lang.String e_id;
	private java.lang.String name;
	private java.lang.String no;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String D_ID = "d_id";
	public static final String E_ID = "e_id";
	public static final String NAME = "name";
	public static final String NO = "no";
			
	/**
	 * 属性d_id的Getter方法.属性名：parentPK
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getD_id () {
		return d_id;
	}   
	/**
	 * 属性d_id的Setter方法.属性名：parentPK
	 * 创建日期:
	 * @param newD_id java.lang.String
	 */
	public void setD_id (java.lang.String newD_id ) {
	 	this.d_id = newD_id;
	} 	  
	/**
	 * 属性e_id的Getter方法.属性名：雇员ID
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getE_id () {
		return e_id;
	}   
	/**
	 * 属性e_id的Setter方法.属性名：雇员ID
	 * 创建日期:
	 * @param newE_id java.lang.String
	 */
	public void setE_id (java.lang.String newE_id ) {
	 	this.e_id = newE_id;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：雇员名称
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：雇员名称
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性no的Getter方法.属性名：雇员编号
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getNo () {
		return no;
	}   
	/**
	 * 属性no的Setter方法.属性名：雇员编号
	 * 创建日期:
	 * @param newNo java.lang.String
	 */
	public void setNo (java.lang.String newNo ) {
	 	this.no = newNo;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "d_id";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "e_id";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "memp";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "memp";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public Emp() {
		super();	
	}    
} 


